# SERSPeakFinder UI settings
# Keys map to lineEdit widgets in main.py / ui_main.py

[split]
# Splite Plot Data
raw_file =
output_dir =

[classify]
# Plot Classifier
data_dir = D:/Py_Codes/raman_analysis/s_data
center_wl = 1000
wl_range = 5

[train]
# CNN Training
data_dir = //bq-nas/Meas_Data/SERS raw data/20241118 serum 4 to10/small_ng_samp4_8
label_file = //bq-nas/Meas_Data/SERS raw data/20241118 serum 4 to10/output file 4 to 10/m6/output small ng samp 4_8.csv
test_size = 0.2
epochs = 1000
random_state = 42
batch_size = 1000
validation_split = 0.2
model_name = small_ng_samp_m6.pth

[detect]
# Run (Peak Detection)
model_path = D:/Py_Codes/raman_cnn/small_ng_samp_m6.pth
data_dir = D:/Py_Codes/raman_analysis/splite_file

[compare]
# Compare with Prev. Plot
model_result = //bq-nas/Meas_Data/SERS raw data/20241118 serum 4 to10/output file 4 to 10/m6/pred_sns10.csv
manual_result = //bq-nas/Meas_Data/SERS raw data/20241118 serum 4 to10/output file 4 to 10/m6/output small ng samp 10.csv
plot_dir = //bq-nas/Meas_Data/SERS raw data/20241118 serum 4 to10/small ng samp 10

[integration]
# Interpolation
report_file = D:/Py_Codes/raman_cnn/m_report.csv
data_dir = D:/Py_Codes/raman_analysis/splite_file
fft_cutoff = 0.2
sg_window = 20
sg_polyorder = 9
center_wl = 1000
wl_range = 5
